// AUTO-GENERATED by python -m scripts.gen_api_types — do not edit.
// Source: backend OpenAPI schema (CT-01 contract guard).

export interface ApiRoute {
  path: string;
  methods: string[];
}

export const API_ROUTES: readonly ApiRoute[] = [
  { path: '/api/v1/addresses/analyze', methods: ["POST"] },
  { path: '/api/v1/addresses/{address}/subgraph', methods: ["GET"] },
  { path: '/api/v1/admin/dead-letters', methods: ["GET"] },
  { path: '/api/v1/admin/dead-letters/{dead_letter_id}/requeue', methods: ["POST"] },
  { path: '/api/v1/admin/judgments/{judgment_id}/cancel', methods: ["POST"] },
  { path: '/api/v1/admin/providers/health', methods: ["GET"] },
  { path: '/api/v1/admin/queues', methods: ["GET"] },
  { path: '/api/v1/admin/reports/{report_id}/cancel', methods: ["POST"] },
  { path: '/api/v1/audit-logs', methods: ["GET"] },
  { path: '/api/v1/auth/login', methods: ["POST"] },
  { path: '/api/v1/auth/logout', methods: ["POST"] },
  { path: '/api/v1/auth/refresh', methods: ["POST"] },
  { path: '/api/v1/cases', methods: ["GET", "POST"] },
  { path: '/api/v1/cases/{case_id}', methods: ["GET", "PATCH"] },
  { path: '/api/v1/cases/{case_id}/addresses', methods: ["POST"] },
  { path: '/api/v1/cases/{case_id}/addresses/{address}', methods: ["DELETE"] },
  { path: '/api/v1/cases/{case_id}/reports', methods: ["POST"] },
  { path: '/api/v1/demo/addresses', methods: ["GET"] },
  { path: '/api/v1/judgments/{judgment_id}', methods: ["GET"] },
  { path: '/api/v1/judgments/{judgment_id}/retrieval-explanation', methods: ["GET"] },
  { path: '/api/v1/patterns', methods: ["GET"] },
  { path: '/api/v1/patterns/{pattern_id}', methods: ["GET"] },
  { path: '/api/v1/reports/{report_id}', methods: ["GET"] },
  { path: '/api/v1/reports/{report_id}/download', methods: ["GET"] },
  { path: '/api/v1/users', methods: ["POST"] },
  { path: '/api/v1/users/{email}', methods: ["PATCH"] },
  { path: '/healthz', methods: ["GET"] },
  { path: '/readyz', methods: ["GET"] },
] as const;
