"""OpenAPI → TypeScript 契约同步（CT-01）。

用法：
    python -m scripts.gen_api_types            # 校验 + 同步生成
生成两个产物：
  1. tests/unit/__snapshots__/openapi.json     # pytest 快照守护源
  2. frontend/types/api.d.ts                   # 前端类型引用（路径清单）
前端 `npm run type-check` 消费该文件；schema 必填字段新增时，
先跑本脚本再跑 type-check，即可复现 CT-01 的漂移失败。
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

SNAPSHOT = ROOT / "tests/unit/__snapshots__/openapi.json"
TYPES = ROOT / "frontend/types/api.d.ts"


def canonical() -> dict:
    from backend.api.app import create_app

    spec = create_app().openapi()
    return {"paths": {k: spec["paths"][k] for k in sorted(spec["paths"])},
            "components": spec.get("components", {})}


def main() -> int:
    spec = canonical()
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(json.dumps(spec, sort_keys=True,
                                   separators=(",", ":")))
    TYPES.parent.mkdir(parents=True, exist_ok=True)
    lines = ["// AUTO-GENERATED by python -m scripts.gen_api_types — do not edit.",
             "// Source: backend OpenAPI schema (CT-01 contract guard).",
             "",
             "export interface ApiRoute {",
             "  path: string;",
             "  methods: string[];",
             "}",
             "",
             "export const API_ROUTES: readonly ApiRoute[] = ["]
    for path in spec["paths"]:
        methods = sorted(m.upper() for m in spec["paths"][path])
        method_list = ", ".join(f'"{m}"' for m in methods)
        lines.append(f"  {{ path: '{path}', methods: [{method_list}] }},")
    lines.append("] as const;")
    lines.append("")
    TYPES.write_text("\n".join(lines))
    print(f"wrote {SNAPSHOT.relative_to(ROOT)} and {TYPES.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
